services:
  freegames:
    container_name: egsfreegames
    build: .
    environment:
      - WEBHOOK_URL=https://discord.com/api/webhooks/redacted
      # Uncomment these if you want to host the images yourself:
      - EPIC_ICON=https://rubberverse.xyz/uploads/egsflogo.png
    volumes:
      - egsfreegames:/home/botuser/.local/share/discord_free_game_notifier/
    security-opt:
      - no-new-privileges
    cap_drop:
      - ALL
    restart: unless-stopped
    
volumes:
  egsfreegames:
